### ISSUE TITLE
[BUG] The docs do not reflect the modification of the graph_match module

### ISSUE THREAD

**Issue by ebridge2** [graspologic-org/graspologic#1042]
## Expected Behavior

The docs align with the new graph matching code

## Actual Behavior

The docs reflect the old graph matching code

## Example Code

https://microsoft.github.io/graspologic/tutorials/matching/padded_gm.html

https://github.com/microsoft/graspologic/blob/39f83aedb797444bbfd778b48db44abe73f17d42/graspologic/match/wrappers.py#L50

## Additional Details
Any other contextual information you might feel is important.

**Comment by bdpedigo** [comment]
the current version of the docs do reflect the new code https://microsoft.github.io/graspologic/latest/tutorials/matching/padded_gm.html

i am not actually sure how you navigated to that page? somehow that is linked to an old version of graspologic
