### ISSUE TITLE
[BUG] Scipy deprecations causing importerrors in gensim

### ISSUE THREAD

**Issue by j1c** [graspologic-org/graspologic#1059]
## Expected Behavior
scipy function `triu` used in `gensim` was deprecated in scipy==1.13.0. Limit scipy version

## Example Code
```python
import graspologic
```

## Full Traceback
```pytb
ImportError: cannot import name 'triu' from 'scipy.linalg'
```

## Your Environment
* Python version:
* graspologic version:

## Additional Details
Any other contextual information you might feel is important.

**Comment by j1c** [comment]
> i noticed [piskvorky/gensim#3524](https://github.com/piskvorky/gensim/pull/3524) - if they get a fix out soon, would be nice to use that instead of banning future scipy releases

Neat. This will probably mean we have to set a minimum to gensim instead then.

**Comment by bdpedigo** [comment]
agreed. thinking about it more, if you want to ban scipy 1.13 in the meantime like in your PR, i have no problem with that. who knows how long they will take to get a fix out.

**Comment by bdpedigo** [comment]
covered in https://github.com/graspologic-org/graspologic/pull/1067
