### ISSUE TITLE
implement divide and conquer graph matching 

### ISSUE THREAD

**Issue by bdpedigo** [graspologic-org/graspologic#391]
[Paper](https://www.sciencedirect.com/science/article/pii/S0167819115000484?casa_token=X3tMYbPTEJAAAAAA:Z5_jOg5IQMWS8DrK17lo6RXc9lEuWIPKfibhLYSA8qA9hwKAQvHq47YHZ6m66wKlskZ-ydYN)

**Comment by Dhavin** [comment]
Hello @bdpedigo   , I would like to contribute to this project by solving this issue. Can I?
