### ISSUE TITLE
Configure CI to push to conda-forge automatically

### ISSUE THREAD

**Issue by bdpedigo** [graspologic-org/graspologic#413]
https://anaconda.org/conda-forge/graspy/files looks outdated, did not update when PyPI did.

**Comment by bdpedigo** [comment]
@loftusa i wonder if this is up your alley 😄 no worries if not

**Comment by loftusa** [comment]
@bdpedigo Possibly, but I'd prefer to work within the codebase itself as much as possible at the moment I think

**Comment by gavinmischler** [comment]
Can you update to graspologic within conda-forge? Or maybe just create a new feedstock? Currently causing an [issue](https://github.com/mvlearn/mvlearn/issues/294) with using mvlearn from conda-forge since only an old version of graspy is available.

**Comment by bdpedigo** [comment]
im for creating a graspologic feedstock but dont have bandwidth to look into right now - I think in an earlier conversation we said we'd only do if we had a way to update feedstock automatically. 

I see according to this https://stackoverflow.com/a/66539742/15480487 that it should be super easy. 

Only caveat is 
> Step 3 : Fork conda-forge/staged-recipes in your user/organization space.
which maybe only @dwaynepryce can do? Or maybe has to get permission to even do?
