### ISSUE TITLE
Advanced tutorial: Embedding central limit theorem (CLT)

### ISSUE THREAD

**Issue by bdpedigo** [graspologic-org/graspologic#442]
Waiting for #419 to expose the estimation of the spectral embedding central limit theorem as a function.

paper: https://link.springer.com/content/pdf/10.1007/s13171-015-0071-x.pdf

will want to explain some of the math/theory and demonstrate with a synthetic data example

**Comment by Jingyan230** [comment]
Is this issue a part of issue #414 ?

**Comment by alyakin314** [comment]
hey @Jingyan230 , it is not (and they aren't directly related).

**Comment by Jingyan230** [comment]
@alyakin314 Thanks.
