### ISSUE TITLE
Advanced tutorial: embedding, alignment, and latent distribution test

### ISSUE THREAD

**Issue by bdpedigo** [graspologic-org/graspologic#443]
Tutorial should describe: 
- spectral embeddings have a non-identifiability (orthogonal transformations in the embedded space) 
- we can use the tools in the align module to circumvent this (both normal procrustes if a vertex alignment is known, or a seedless procrustes if not) 
- with these tools, latent distribution test for finite samples becomes tractable

**Comment by alyakin314** [comment]
related to #177.

**Comment by alyakin314** [comment]
of some relevance:
https://nbviewer.jupyter.org/url/alyakin314.github.io/assets/seedless_2.ipynb
also, Ali, cep and YP have another simulated example in which it is required to use seedless to do sound inference.
