### ISSUE TITLE
Advanced tutorial: OMNI vs MASE

### ISSUE THREAD

**Issue by bdpedigo** [graspologic-org/graspologic#444]
need to talk to @jesusdaniel and others about what simulation settings will best explain the differences/tradeoffs

**Comment by PerifanosPrometheus** [comment]
I could take this one!

**Comment by bdpedigo** [comment]
@PerifanosPrometheus ok, i suggest you discuss with everyone else still interested in tutorial issues and come up with a plan. fair warning that for this one, I am not totally sure what simulation settings will help show the difference between the two algos. So there will be a fair bit of digging involved to figure out what to show. but i do think this is a feasible task for a semester

**Comment by PerifanosPrometheus** [comment]
@bdpedigo Thank you for your suggestion! 

@jesusdaniel Would you be willing to discuss via e-mail or via zoom call possible simulations settings that could best explain these differences

**Comment by jesusdaniel** [comment]
@PerifanosPrometheus sure. There are some ideas to start in this paper: https://arxiv.org/pdf/2008.10055.pdf . The main inference task there is on hypothesis testing, but I believe that some of these results also hold in other tasks (classification, clustering, etc.)

**Comment by PerifanosPrometheus** [comment]
@jesusdaniel Thank you very much for the resource provided

**Comment by bdpedigo** [comment]
https://arxiv.org/pdf/2005.02511.pdf
https://jmlr.org/papers/volume18/17-448/17-448.pdf
https://arxiv.org/abs/1906.10026

**Comment by PerifanosPrometheus** [comment]
Definition of Done(DoD) for the issue:

1. Introduce differences between MASE and OMNI
2. Explain when and why MASE would perform better than OMNI in certain tasks and vice versa. List each scenario and preferred embedding method for the listed scenarios. (If possible, find some objective metric to quantify each of these statements)
3. Bring one example where MASE would be more suited for a certain task
4 Bring one example where OMNI would be more suited for a certain task
(5. Possibly bring one example using real dataset)

@bdpedigo feel free to reach out with suggestions and/or critiques
