### ISSUE TITLE
Documentation Questions: install.rst

### ISSUE THREAD

**Issue by daxpryce** [graspologic-org/graspologic#479]
I'm updating all the naming stuff now (at least in a first pass), and I'm taking note of some of the places where the graspy approach differs from the topologic approach. I am registering issues at each of these places so we can have a conversation about what our actual approach should be going forward and how best to execute a merger.

In this specific placeholder issue, I'm wanting to talk about the install.rst file.  Mostly I want to talk about whether it makes sense to have this duplicated in both the README and this file.  Should the documentation generated point back to the readme?  Should the readme just defer to the generated documentation?

**Comment by j1c** [comment]
If you mean having documentation point to the readme.md file in github, I would prefer not to do this. So i would advocate for readme pointing to the documentation. If we switch to rst for readme, we can just include the install.rst into the readme. Im not sure if there is a way to do this if readme is markdown.

I think in general, I wouldn't want my documentation link to things outside of the website (if that makes sense).

**Comment by dwaynepryce** [comment]
It does.  The good news is you can use markdown in your sphinx documentation generation - I refuse to write any RST if I can at all get away with it, so we actually do most of our non-autodoc stuff in markdown in topologic.

We can probably just include those markdowns from outside the docs folder somehow so we don't have to replicate them - that way at build we can keep a snapshot of where that contributing/readme/whatever file was at that moment vs. pointing to a live file.

**Comment by dwaynepryce** [comment]
https://github.com/microsoft/topologic/tree/dev/docs is where our docs are if you wanted to poke around and see what I'm talking about.  Rendered output is on RTD

**Comment by bdpedigo** [comment]
> If you mean having documentation point to the readme.md file in github, I would prefer not to do this

Agree w @j1c on this

> We can probably just include those markdowns from outside the docs folder somehow so we don't have to replicate them - that way at build we can keep a snapshot of where that contributing/readme/whatever file was at that moment vs. pointing to a live file.

This would be for having something in the readme that just pulls from another file? If so, that would be cool, but I also don't see any issue with just having 2-3 really quick install instructions on the readme that are hard-coded and will likely almost never change (pip install/conda install) and then more extensive instructions (and tips for people who are new to python, for example) on the actual docs. I get that we don't want to redouble effort but I feel like this could be more trouble than its worth in this case.
