### ISSUE TITLE
Enable Doctest in unit and doctest phase of build pipeline

### ISSUE THREAD

**Issue by daxpryce** [graspologic-org/graspologic#514]
Doctests were failing when running pytest before, across all Python versions and OSes.  They should not!  We should fix those, and make a failing doctest invalidate a mergable PR

**Comment by bdpedigo** [comment]
@dwaynepryce i cant remember if this one ever got fixed?

**Comment by dwaynepryce** [comment]
I can't either - I know I didn't look into it too much at the time - they just didn't work when we first merged?  We should make it a point to re-enable them and fix whatever is broken.

**Comment by daxpryce** [comment]
@jonmclean if you could look into this, I would really appreciate it
