### ISSUE TITLE
Add option to utilize numpy.random.Generator object in sample_edges

### ISSUE THREAD

**Issue by PerifanosPrometheus** [graspologic-org/graspologic#603]
## Issue:
 Sample_edges utilizes numpy.random.RandomState, would be nice to be able to utilize a numpy.random.Generator object as well. 

## Solution:
Add option input to sample_edges that accepts a numpy.random.Generator object. If this input is provided then sample_edges should use the numpy.random.Generator object to sample from bernoulli. 

## References
[numpy.random.Generator](https://numpy.org/doc/stable/reference/random/index.html?highlight=random%20sampling%20numpy%20random#module-numpy.random) is the newly adopted pseudo-random number generator utilized and maintained by numpy. Check out [here](https://numpy.org/doc/stable/reference/random/legacy.html#numpy.random.RandomState) in the numpy doc the compatibility guarantee for numpy.random.RandomState which is what is currently being used.

**Comment by PerifanosPrometheus** [comment]
@bdpedigo I opened the new issue to add this feature. 

Please let me know if it is still something desirable.

**Comment by bdpedigo** [comment]
issue looks good, are you planning on adding this to `sample_edges` somehow?

**Comment by PerifanosPrometheus** [comment]
Yes, my plan is to add as input the random.number.Generator to the sample_edges. If this input isn't given  that function work as it is , if the input is given than use the provided object.
