### ISSUE TITLE
Make SVD code faster

### ISSUE THREAD

**Issue by loftusa** [graspologic-org/graspologic#734]
I've found that [scipy's implementation of the lanczos algorithm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html) is extremely fast for finding eigenvalues and eigenvectors of a big, sparse real symmetric square matrix (I'm pretty sure more so than sklearn's `randomized_svd` or scipy's `sparse.linalg.svds`, although this all needs to be tested empirically).

in the case of undirected graphs, our adjacency matrices are going to be square and symmetric, so the singular values will be the eigenvalues (right?), and most of them are going to be pretty sparse

So a potential NDD project could be testing the various algorithms for finding eigenvalues, eigenvectors, and more generally doing SVDs for speed, on different types of matrices, and then using the ones that are fastest in e.g. [SelectSVD](https://github.com/microsoft/graspologic/blob/dev/graspologic/embed/svd.py#L173), and then adding some blurb in the docs about when it is appropriate to use which algorithm.

**Comment by rajpratyush** [comment]
@loftusa lanczos algorithm here refers to  the danielson lanczos lemma or lanczos method for gamma functions or is it a different thing if so please provide me some reference materials to go through

**Comment by loftusa** [comment]
@rajpratyush Implicitly Restarted Lanczos Method: https://link.springer.com/article/10.1007/s11075-006-9057-z

Also see the references in scipy.sparse.linalg.eigsh: https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html#id1

**Comment by bdpedigo** [comment]
#579 is related, they have lots of this stuff i think. also i think there are some tricks for laplacians that can make them faster to decompose using linear operators (will have to look at their code for more details)

**Comment by bdpedigo** [comment]
https://github.com/microsoft/graspologic/issues/208 is probably a smarter thing to tackle first

**Comment by rajpratyush** [comment]
@loftusa does implementing joblib here would help??

**Comment by loftusa** [comment]
> @loftusa does implementing joblib here would help??

don't think so

**Comment by rajpratyush** [comment]
I am going for #208 first

**Comment by rajpratyush** [comment]
Restarted Lanczos Method: https://link.springer.com/article/10.1007/s11075-006-9057-z

https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.1478

I cannot read these articles. Can you help ?@loftusa

**Comment by loftusa** [comment]
> Restarted Lanczos Method: https://link.springer.com/article/10.1007/s11075-006-9057-z
> 
> https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.1478
> 
> I cannot read these articles. Can you help ?@loftusa

https://sci-hub.se/
