### ISSUE TITLE
Make homepage cool

### ISSUE THREAD

**Issue by bdpedigo** [graspologic-org/graspologic#740]
## Is your feature request related to a problem? Please describe.
Lots of libraries have "cool looking" homepages with logos or graphics, makes them look legit

## Describe the solution you'd like
At least come up with a logo, ideally some cool visuals also (see #565, related)

## Provide references (if applicable)
Some references of packages with "cool looking" stuff
https://graph-tool.skewed.de/
https://networkx.org/
https://scikit-network.readthedocs.io/en/latest/

## Additional context
cc @jovo as this came out of a convo with him

**Comment by sagarhowal** [comment]
I could try and come up with a logo. 

Did you have any logos for GraSPy and Topologic? Maybe they can be merged in some way. 

![PXL_20210325_133935168~2.jpg](https://user-images.githubusercontent.com/22494944/112526306-b3bdb880-8d99-11eb-91c9-262743fb8ebc.jpg)


This is a doodle something off the top of my head. 

Do you already have any ideas/concepts you want the logo to incorporate?

**Comment by bdpedigo** [comment]
@sagarhowal that's great, we'd appreciate any help/input. And no, we didn't have preexisting ideas. But I like your doodle!

I'm wondering if we deleted the edges that are outside of the G, but still had edges inside in another color (we were thinking maybe a light blue?). We could use just the "G" that looks like a network for the logo in the sidebar and such, and then could also have a version where "graspologic" is written out with you G. 

Do you have any experience with rendering/drawing logos like this? Or how do you suggest proceeding? Since this idea is simple enough we could also try to make it in matplotlib 😆 

(I don't speak for everyone on the team, if anyone else has ideas please chime in!)

**Comment by bdpedigo** [comment]
i do note that we've thus far mostly been using graspologic (lower case) instead of Graspologic - personally I don't care much, and I think the G above looks cool. if anyone disagrees, i guess we could also try a lower case graph-g

**Comment by sagarhowal** [comment]
@bdpedigo Glad you liked it. I can try something with a lowercase g and also the uppercase G without the edges outside the G. Yes, I do have some experience but it is mostly a hobby, i know a few things about vector graphics and typography but i am mainly a developer. 

I love the idea of making this in matplotlib. Someone could give it a go 😅. It will eventually need to be converted to a vector graphic and you will need to test several sizes, test to see if it looks good in black-and-white, it will have to be tested for colour blindness. That's a few things that are standard for logos.

**Comment by sagarhowal** [comment]
> Or how do you suggest proceeding?
I can make this using an open-source vector design tool. And (optional) in a repository like this one https://github.com/hpe-design/logos. I will leave the ways on how to collaborate/vote on the logo to you.

**Comment by sagarhowal** [comment]
I tried doodling the lowercase g. Since it has more curves, it needs more nodes. It could look confusing if the logo is used in a low resolution. 

But it does look better to me. 😅
Thoughts?

![small_g_graspologic_crop_small](https://user-images.githubusercontent.com/22494944/112618813-73544e00-8e1e-11eb-8f2c-388ed1eb38f9.jpeg)

**Comment by bdpedigo** [comment]
> I tried doodling the lowercase g. 

So far I think I like the uppercase better, if we do end up wanting lowercase later we'd probably just have to play with the shape/edges a lot.

> I can make this using an open-source vector design tool. 

That would be awesome!

**Comment by bdpedigo** [comment]
> I love the idea of making this in matplotlib. Someone could give it a go 😅.

Maybe we play with this once the design is settled more, I'd be happy to try at some point.

>  It will eventually need to be converted to a vector graphic and you will need to test several sizes, test to see if it looks good in black-and-white, it will have to be tested for colour blindness. That's a few things that are standard for logos.

Yes totally agree!

**Comment by rflperry** [comment]
Or rather than matplotlib, you could draw a pointcloud `G` (with some edges based on the G shape) and graph match an actual graph to it, using the matched pointcloud coordinates to make the layout.

**Comment by dwaynepryce** [comment]
So, I like these ideas, but I also remember a vertexified Google G in a logo and I don't think Microsoft is going to want to go anywhere near that under any circumstances.

I'll get a conversation started on our end on what we need to be aware of / are allowed to do!

**Comment by sagarhowal** [comment]
After you mentioned I can't unsee the capital G resembling google. 

I have a draft for the small g. 
I'll just post it here for the time being while you sort out what are allowed to do. 

Draft-- 
![graspologic-logo-v0 0 1](https://user-images.githubusercontent.com/22494944/112723757-0d43f580-8f08-11eb-9f5c-cf89ed76852a.jpeg)

**Comment by loftusa** [comment]
Something like this is another option - could iterate on this (e.g., change the font for the G, add extra stuff, whatever)
![graspologic_logo](https://user-images.githubusercontent.com/12386450/112736241-9d456780-8f27-11eb-9a2e-cca50ffbbc20.png)

**Comment by loftusa** [comment]
idk
![graspologic_logo2](https://user-images.githubusercontent.com/12386450/112736394-a420aa00-8f28-11eb-8eee-ded4acd97883.jpg)

**Comment by loftusa** [comment]
although looking back I kinda like @sagarhowal's design a little more, I think it's a bit more simple and clean

**Comment by ahoak** [comment]
@dwaynepryce mentioned this ticket to me on Friday. I see you have a couple designs already which are totally awesome, I had started working on a concept Friday and thought I would share (and you totally don't have to go with this, just want to present options). I can supply original illustrator file and SVG, or other image format. Also happy to make any changes. This is currently using: https://docs.microsoft.com/en-us/typography/font-list/bahnschrift. 
![graspologic_v6@300x](https://user-images.githubusercontent.com/21273003/112870749-5e242d00-9073-11eb-879d-63ddeefad8f1.png)

**Comment by loftusa** [comment]
Ooh, I love that one @ahoak, network thing in a circle looks really good. I'd probably advocate for changing the G? Either lowercase or a different font

**Comment by dwaynepryce** [comment]
@ahoak had an example as lower case and it looked a little more jarring (the G in this one kinda brings the circle into the center, since it's reminiscent of a circle itself).  The baby G looked a bit out of place (but she can show you and you can draw your own conclusions ;D)

**Comment by bdpedigo** [comment]
> So, I like these ideas, but I also remember a vertexified Google G in a logo and I don't think Microsoft is going to want to go anywhere near that under any circumstances.

Do we know how microsoft will feel about big Gs? Or I guess what I am asking is what the criteria are to make a big G okay?

**Comment by dwaynepryce** [comment]
@natoverse - where do we officially stand on capital Gs?

**Comment by carolyncb** [comment]
I will run the capital G question by our legal team and see what I find out!

**Comment by jovo** [comment]
I love the G and g ideas.  That said, it might be worth considering some 'non-g' ideas?

**Comment by jovo** [comment]
Like a hand grasping made out of logic/network?

**Comment by dwaynepryce** [comment]
us:

> we've tried absolutely one letter and we're out of ideas

jovo:

> what about other letters?

us: 

> https://media.giphy.com/media/2rqEdFfkMzXmo/giphy.gif

**Comment by ahoak** [comment]
Here is a couple options that dont include "g" .  I was thinking about Jovo's comment , It could be interesting to have an octopus arms  composed of graph nodes grasping the text  as an alternative idea. 
> Like a hand grasping made out of logic/network?

![graspologic_v10@300x](https://user-images.githubusercontent.com/21273003/112930186-b0df0280-90ce-11eb-9f6b-7834230e0e3d.png)

**Comment by dwaynepryce** [comment]
Octopodes are just nodes with degree 8 change my mind

**Comment by bdpedigo** [comment]
big fan of exploring the abstract octopus with nodes/edges idea

**Comment by dwaynepryce** [comment]
joking aside, I am also a fan of having the log next to the text of the name too.  that neatly sidesteps the concerns I was raising earlier for sure, and ... I just like it more.

**Comment by j1c** [comment]
> joking aside, I am also a fan of having the logo next to the text of the name too. that neatly sidesteps the concerns I was raising earlier for sure, and ... I just like it more.

Quite like the logo next to text as well!

**Comment by bdpedigo** [comment]
![bad-drawing](https://user-images.githubusercontent.com/25714207/113030456-9c951700-915b-11eb-9874-0f79f83c99bc.jpeg)
(don't laugh at my bad drawing) just throwing ideas out - i wonder how abstract/simple the octopus could be such that you could still tell its an octopus? Here i was thinking of Dwayne's 8-degree-node-octopus, I obviously don't think what I have is pretty or octopus-like enough, but maybe someone knows how to fix that? 

I also really like the octopus grabbing logo idea, only thing i worry about is whether it would get too complicated for a logo

**Comment by bdpedigo** [comment]
`graspoloctopus` really rolls off the tongue too

**Comment by sagarhowal** [comment]
> do you have like a PSD or illustrator file for that @sagarhowal?

I made these quick ones in Gravid Designer. It is a free tool. Not very professional. If you like I can make it in inkscape and share. Thanks @loftusa 


I like @ahoak's ideas. they're all great. If the node connections were slightly thinner, it would look good in low resolution. 


I think exploring @jovo's idea of not having a g at all sounds good too. 

Also, I was also thinking of an octahedron shaped graph where every side makes the letter G (if that makes sense). I tried bt couldn't make it. If anyone wants to give it a go.

**Comment by sagarhowal** [comment]
@bdpedigo here's something for you i made quickly. 😅😁
![graspo-bpedigo](https://user-images.githubusercontent.com/22494944/113042434-18f71c80-9193-11eb-8c6b-655adb3b2962.png)

**Comment by loftusa** [comment]
> joking aside, I am also a fan of having the logo next to the text of the name too. that neatly sidesteps the concerns I was raising earlier for sure, and ... I just like it more.

thirded

**Comment by loftusa** [comment]
this one's my favorite so far @ahoak. Do you have the illustrator file for that? I have a few ideas I want to play around with

> ![graspologic_v10@300x](https://user-images.githubusercontent.com/21273003/112930186-b0df0280-90ce-11eb-9f6b-7834230e0e3d.png)

**Comment by ahoak** [comment]
I have a couple of experiments with the octopus 
![octo_arm_gL_v2@300x](https://user-images.githubusercontent.com/21273003/113071926-9d897100-917a-11eb-8f20-de05207c9732.png)
![octo_arm_purplev4@300x](https://user-images.githubusercontent.com/21273003/113071929-9e220780-917a-11eb-8a4f-ec15598d0a37.png)
![octo_arm_gl_v3@300x](https://user-images.githubusercontent.com/21273003/113071927-9e220780-917a-11eb-804a-ac878af4b9a3.png)

I also did this one for fun:
![graph_octo2@300x](https://user-images.githubusercontent.com/21273003/113071969-b8f47c00-917a-11eb-869c-e6ff206e471c.png)

**Comment by ahoak** [comment]
> this one's my favorite so far @ahoak. Do you have the illustrator file for that? I have a few ideas I want to play around with
> 
@loftusa  I attached a zip file with the Illustrator file you requested and an SVG version in case for some reason that doesn't work or you prefer to use another tool. 




[logo_graspologic_art.zip](https://github.com/microsoft/graspologic/files/6233033/logo_graspologic_art.zip)

**Comment by jovo** [comment]
getting very interesting! i think the 4 tentacles reminds me a bit too much of github maybe?

**Comment by ahoak** [comment]
> getting very interesting! i think the 4 tentacles reminds me a bit too much of github maybe?

Yeah for sure! It is too large for a logo as well but I thought I'd throw it out there in case it sparked any ideas.

**Comment by loftusa** [comment]
my vote is on @ahoak's circle one

**Comment by jovo** [comment]
i like the ones with a tentacle grabbing the graspologic word: https://github.com/microsoft/graspologic/issues/740#issuecomment-810657865
reminds me of this: https://www.youtube.com/watch?reload=9&v=3s0LTDhqe5A
but not github or google too much.

**Comment by bdpedigo** [comment]
my vote is also tentacle grabbing word, i really like the 3rd one, but im sure we could play with colors and other details more. 

my only concern is whether we could find a way to simplify it for certain settings (e.g. where the logo would need to be small)?

awesome work @ahoak!

**Comment by loftusa** [comment]
Playing around with @ahoak's circle designs a little bit

![graspologic_logo_art_only_big](https://user-images.githubusercontent.com/12386450/113305511-1bf82700-92d1-11eb-9a56-626e009d148a.png)

![graspologic_logo_art_four_big](https://user-images.githubusercontent.com/12386450/113305522-1e5a8100-92d1-11eb-96ca-5031490baac6.png)

**Comment by jovo** [comment]
those seem less 'graphy' to me, no?

**Comment by dwaynepryce** [comment]
> ![octo_arm_gl_v3@300x](https://user-images.githubusercontent.com/21273003/113071927-9e220780-917a-11eb-804a-ac878af4b9a3.png)

My vote is this one

**Comment by loftusa** [comment]
> those seem less 'graphy' to me, no?

yeah, but a little more simple

**Comment by loftusa** [comment]
> > ![octo_arm_gl_v3@300x](https://user-images.githubusercontent.com/21273003/113071927-9e220780-917a-11eb-804a-ac878af4b9a3.png)
> 
> My vote is this one

I do like that one, but 

> my only concern is whether we could find a way to simplify it for certain settings (e.g. where the logo would need to be small)?

also concerned about this

**Comment by dwaynepryce** [comment]
@ahoak maybe better in my mind's eye than reality, but what if the octopus arm were mirrored to the other side and mostly behind all the text except the g?  it would make it more compact and also act as a kind of underline.  then it would ALSO potentially be even _more_ graspy.

For the rest of you, this is kinda super sweet for us, because our team's mascot is an octopus (named wiggleton, in case you were wondering), and graspy was your baby first, and it's got a lot of symbolism going both ways and I like it somuch

**Comment by bdpedigo** [comment]
just a thought but we could also have a complicated/cool version and a simple version, i just dont know what the simple version would be (e.g. imagine what the favicon for this would be? cause i have no idea)

i agree that the octopus symbolism is multiple layers of cool!

**Comment by carolyncb** [comment]
My favorite is also the tentacle grabbing the word. From the minimalist octopus vector graphics that @loftusa suggested, I liked this one: 
![image](https://user-images.githubusercontent.com/60894394/113338629-35ec3680-92de-11eb-9479-418b88ce87d3.png)

**Comment by ahoak** [comment]
I will work today on simplifying a few of these concepts.  
@loftusa I like the minimalist idea you have and open to collab.

**Comment by dwaynepryce** [comment]
To try to make this go a bit more smoothly, I added an extra half hour to our monthly status meeting for **Monday, April 5th, 2021**.  

I added @loftusa to it because I had his email, but if anyone else wants to be part of it, please have @bdpedigo or @j1c forward the meeting invite to you (presuming they have your email, at least.  Otherwise, @ me)

**Comment by bdpedigo** [comment]
good idea, thanks!

**Comment by ahoak** [comment]
![graspologic_arm_simplified@300x](https://user-images.githubusercontent.com/21273003/113371302-e37d3b00-931a-11eb-8b0c-f2b61e675726.png)
Here is a less complex version of the octopus arm

**Comment by ahoak** [comment]
Here is a combined view of the different concepts with associated flavicon for tomorrow's meeting. Let me know if I missed anything! 
![graspologic_logo_options@300x](https://user-images.githubusercontent.com/21273003/113521785-908cc900-9550-11eb-83bd-3d4a00610b58.png)

**Comment by loftusa** [comment]
> Here is a combined view of the different concepts with associated flavicon for tomorrow's meeting. Let me know if I missed anything!

Awesome! My favorite is #1 and #3. I like #3 for the octopus symbology, and #1 because it's more circular/compact

**Comment by jovo** [comment]
They are all great, I love 4 the most.  I agree with @dwaynepryce that it might be cool to see the tentacle flipped so that it is fully under the word graspologic, maybe so graspologic looks like it is floating on the arm?

**Comment by loftusa** [comment]
dark horse hot take: take the [hydra logo](https://www.google.com/search?q=hydra+logo&newwindow=1&sxsrf=ALeKk01F7ALlYgn79txo-Tw9-U23dFqCYQ:1617645683964&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiytfXi1-fvAhUmMlkFHUcFBykQ_AUoAXoECAEQAw&biw=1792&bih=990) from the Marvel universe, make it look not-menacing and not have a skull and change the color scheme, and network-ify it

**Comment by loftusa** [comment]
@ahoak got illustrator files for the new stuff? 😇

**Comment by ahoak** [comment]
Sorry I haven't gotten a chance to follow up after our last convo. Do you like this? If so, which color? @loftusa I can provide illustrator files of this if you would like. 
![grasp_logo_final_options_1@300x](https://user-images.githubusercontent.com/21273003/114326476-d6fe9c80-9ae9-11eb-96fc-be19215674fc.png)

**Comment by jovo** [comment]
i totally love it! especially the bottom one is my fav so far!

**Comment by ahoak** [comment]
@carolyncb submitted the bottom two designs for review through our legal team on April 21st and we are still waiting on their response .

**Comment by bdpedigo** [comment]
hey @ahoak and @carolyncb! just wanted to pick this conversation back up and see whether you have heard anything from the legal team?
