### ISSUE TITLE
Add citation.cff file

### ISSUE THREAD

**Issue by bdpedigo** [graspologic-org/graspologic#867]
https://citation-file-format.github.io/

If we add one of these to our root directory, github will create a little button that makes it easy for people to cite. 

Example of this in action: https://github.com/neurodata/hyppo

**Comment by daxpryce** [comment]
My main concern is trying to keep the version updated at the same time we do releases and such.  It seems like a lot of these things expect versions to change very rarely and via a manual process, which is not really what our release process is about (frequent, automated, etc)

I'm not against it, but I'd hate for us to have a new Issue every few months telling us that our version is citation.cff'd @ 1.2.3 and we're on 4.5.6 now

**Comment by bdpedigo** [comment]
I was going to look into redirecting people to the paper via https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#credit-redirection rather than actually having the citation.cff stay up to date/versioned.

**Comment by bdpedigo** [comment]
in other words this would just be a fancy (though prominently displayed on the github) way of asking people to cite via the normal paper route

**Comment by daxpryce** [comment]
sounds totally reasonable then!

**Comment by daxpryce** [comment]
Do you want to build this out?  I have no idea what citations even look like.  I probably haven't paid attention to one since university or highschool

**Comment by bdpedigo** [comment]
yup, this one's definitely on me!
