### ISSUE TITLE
Add Inhomogeneous ER to docs

### ISSUE THREAD

**Issue by ebridge2** [graspologic-org/graspologic#872]
## Is your feature request related to a problem? Please describe.
Inability to simulate from IER model.

## Describe the solution you'd like
Ability to simulate from IER model.

## Provide references (if applicable)
Dos and Don'ts paper.

**Comment by bdpedigo** [comment]
https://github.com/microsoft/graspologic/blob/005c44d434f7874d9a6e3db35637eba19c72ac7f/graspologic/simulations/simulations.py#L20

I think we just need to add this to docs, currently is semi-private

**Comment by bdpedigo** [comment]
could also update the name)

**Comment by ebridge2** [comment]
Looks like a perfect solution to me. Sorry for late reply!
