### ISSUE TITLE
Fix Zenodo DOI

### ISSUE THREAD

**Issue by bdpedigo** [graspologic-org/graspologic#887]
Currently the Zenodo DOI is outdated

needs to be fixed (we think by someone with more admin privileges than myself or @j1c) based on https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

cc @daxpryce we are unsure if this is something only you can do? can chat about it tomorrow at status meeting if need be

**Comment by daxpryce** [comment]
So I went to do this, and I came up against this:
![Screen Shot 2021-11-18 at 1 22 10 PM](https://user-images.githubusercontent.com/899411/142502191-1985e81e-7cf4-433c-94fe-cbb6cb85f537.png)

As you can probably see, someone already asked for it under Microsoft - and nobody seems to have accepted it yet?  I'm not entirely convinced that MSFT is going to go for this in the org (I don't even know who to start asking, but I can see if anyone has any ideas and see if it goes anywhere).

**Comment by daxpryce** [comment]
![Screen Shot 2021-11-18 at 1 47 41 PM](https://user-images.githubusercontent.com/899411/142502420-d7458cad-8b0d-4789-ba39-0f1f8d1a8029.png)

I tried to take a stab at this and ... it looks like someone from Microsoft has to approve the access already. I've done it, but it only gives Zenodo access to my personal stuff - not the organizations.

So I'm not confident this is going to be easily solvable - I'll try to find someone who might be able to approve access like this, but it's not super apparent to me who that might be.

**Comment by jeffwilcox** [comment]
@daxpryce can you send me the URL offline that you took this screenshot from?
