### ISSUE TITLE
Inconsistent IO spec for node2vec

### ISSUE THREAD

**Issue by ebridge2** [graspologic-org/graspologic#934]
The entire package accepts adjacency matrices, but node2vec only accepts `nx` Graphs. This seems very undesirable since the package is not cohesive in this sense.

https://microsoft.github.io/graspologic/latest/_modules/graspologic/embed/n2v.html#node2vec_embed

**Comment by daxpryce** [comment]
Agreed, we had discussed moving node2vec out and into the pipeline package a while back but didn't get down to it.

**Comment by bdpedigo** [comment]
duplicate
