### ISSUE TITLE
symmetrize binary graph

### ISSUE THREAD

**Issue by jovo** [graspologic-org/graspologic#940]
same as 'avg', but then round somehow? or make it clear that we report weighted graph?

**Comment by bdpedigo** [comment]
@hugwuoke something you could work on

**Comment by bdpedigo** [comment]
@hugwuoke this is the current function https://github.com/microsoft/graspologic/blob/9635f7998a0117dab0ad81235904d2d83c89e0bd/graspologic/utils/utils.py#L288
